### ISSUE TITLE
データベース構造の決定

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web-api#1]
~~現在想定しているデータベース構造です。~~
**変更あり、コメント参照ください**
# organizations
- 団体の基礎情報を格納
- **予めこちらで登録し、基本的には変更しない**
- 主キー： organizationId

**organizationId** | organizationName | organizationType | activityType
-- | -- | -- | --
団体ID<br>（既存システムで付与済みのもの） | 団体名 | 団体種別<br>（一般学生団体・課外活動団体） | 活動種別<br>（芸術系・文化系・体育系）

# organization-data
- 各団体が編集するデータを格納
- 主キー： organizationId

organizationId | posterPdfFileName | posterImageFileName | activityIntroduction | website | twitter | instagram | 
-- | -- | -- | -- | -- | -- | --
団体ID<br>（既存システムで付与済みのもの） | ポスターPDFのファイル名 | ポスター画像のファイル名 | 活動紹介 | WebサイトURL | Twitterスクリーンネーム | Instagram ID

# organization-data-other-image
- 各団体のポスター以外の画像のファイル名を格納
- 主キー： organizationId, otherImageFileName

organizationId | otherImageFileName
-- | --
団体ID<br>（既存システムで付与済みのもの） | その他画像のファイル名

# organization-members
- 団体とユーザの紐付け
- 主キー： UID, organizationId

UID | organizationId
-- | --
ユーザーUID（Firebaseから付与） | 所属団体の団体ID

# organization-members-invited

invitationId | mail | organizationId
-- | -- | --
招待ID | メールアドレス<br>（sアドレス） | 団体ID

**Comment by AsagaKosho** [comment]
@nandenjin 確認お願いします！

**Comment by nandenjin** [comment]
* 表記ゆれ？
  * テーブル名の単数複数に揺れがある（`image`だけ単数）
  * (`U`)`ID`と`Id`で略し方に一貫がない（個人的には`member`の一意識別子を"`user`"`Id`と呼ぶのも違和感あるので、こちらを`UID`->`id`で統一した方が丸いかな？）
* `organizations`: 名前とテーブル名に重複があるの無駄では（`organizationId`->`id`, `organizationName`->`name`, 以下同様）
* `organization-data`: 一意なPrimaryKeyが存在しないと、削除・アップデートの時にまずいことにならない？
* `organization-members-invited`: この名前だと`organization-members`のテーブル上に`is_invited`のフラグを立てればいいだけの存在になってしまう
  * 実際は`organization-members`の拡張ではない（識別子は`UID`ではなく`invitationId`）
  * テーブル名`organization-member-invitations`、識別子を`id`にするのが丸いかな？

**Comment by nandenjin** [comment]
なんかちゃんとした命名規則の資料ないかな〜と思ったらこういう感じのがありました🤔

* [データベースオブジェクトの命名規約 - Qiita](https://qiita.com/genzouw/items/35022fa96c120e67c637)

この内容で抵触しそうな物は以下の通り

* 大文字を使わない
* スネークケースで命名する
* 略名を利用しない（`UID`）
* `created_at`, `updated_at`をいれる

稲田もあんま詳しいわけじゃないので他の文献も受付中:pray:

**Comment by AsagaKosho** [comment]
# organizations
- 団体の基礎情報を格納
- **予めこちらで登録し、基本的には変更しない**
- 主キー： organization_id

**organization_id** | organization_name | organization_type | activity_type | created_at | updated_at 
-- | -- | -- | -- | -- | --
団体ID<br>（既存システムで付与済みのもの） | 団体名 | 団体種別<br>（一般学生団体・課外活動団体） | 活動種別<br>（芸術系・文化系・体育系） | データ入力日時 | データ更新日時

# organization_data
- 各団体が編集するデータを格納
- 主キー： organization_id

organization_id | poster_pdf_filename | poster_image_filename | activity_introduction | website | twitter | instagram | created_at | updated_at 
-- | -- | -- | -- | -- | -- | -- | -- | --
団体ID<br>（既存システムで付与済みのもの） | ポスターPDFのファイル名 | ポスター画像のファイル名 | 活動紹介 | WebサイトURL | Twitterスクリーンネーム | Instagram ID | データ入力日時 | データ更新日時

# organization_data_other_image
- 各団体のポスター以外の画像のファイル名を格納
- 主キー： organization_id, other_image_filename

organization_id | otherImage_filename | created_at
-- | -- | --
団体ID<br>（既存システムで付与済みのもの） | その他画像のファイル名 | データ入力日時

# organization_members
- 団体とユーザの紐付け
- 主キー： user_id, organization_id

user_id | organization_id | created_at
-- | -- | --
ユーザーID（Firebaseから付与） | 所属団体の団体ID | データ入力日時

# organization_member_invitations
- 団体への招待中の未登録ユーザ

invitation_id | mail | organization_id | created_at
-- | -- | -- | --
招待ID | メールアドレス<br>（sアドレス） | 団体ID | データ入力日時

**Comment by AsagaKosho** [comment]
@nandenjin 再度確認いただければ～～！

**Comment by AsagaKosho** [comment]
@yuki-js もおねがいします！

**Comment by nandenjin** [comment]
@asagatto777 

* `updated_at` がないテーブルがあるのはどういう意図です？
  * 「絶対に変更できてはならない」という積極的理由がなければ、変更を前提に作っておくのが良いかと思います
* 表記ゆれ
  * `organization_data_other_image` vs `otherImage_filename`

（以下は指摘漏れでした……🙏）

* `organization_members`, `organization_member_invitations` : `mail` -> `email`の方が正確かと思います
* `organization_data` の `data` が抽象的で事実上意味を持っていない
  * これが抽象的な命名であるがゆえに、なんでも入れられるデータモデルになってしまっている
  * 旧サイトの構造に起因する一時的なデータ型であるにしても、その名前（「ページ」とか）を作るべき
  * このテーブルがあくまで団体に紐づく情報の集合であるとするにしても、ポスターは団体の属性ではなく、独立した実体なので別テーブルであるべきでは？（データ型の制約的に`other_images`だけ分離されたけど、本来全てがこうあるべきだった）

変更されなかったこれ↓についてはどういう意図ですか？🤔

> * `organizations`: 名前とテーブル名に重複があるの無駄では（`organizationId` -> `id` , `organizationName` -> `name`, 以下同様）

**Comment by yuki-js** [comment]
結局Firebaseを使うの？

長らくRDBを使っておらずドキュメント思考NoSQL的な志向をしてしまうせいか、organization-data-other-image, organization-membersあたりがしっくりこない

あと団体が提供する画像やPDFは重そうだからCDNに変更することも想定してfilenameじゃなくurlにしたほうがいいと思う

**Comment by AsagaKosho** [comment]
@yuki-js  
認証とユーザ情報の管理についてはFirebaseを使って、その他はSQLを使おうかなと考えてる。
今後もし構成を変更するようなことがあった場合にデータの移行とかをやりやすいようにするためです。
（ @nandenjin によるとFirebaseだとデータの書き出しがしにくいよう）

CDNに変更することも想定して、filenameにしてます。
URLで入れるとURLの変更があればDBを書き換えないといけないが、filenameで入れておくとAPIもしくはフロントの処理部分の書き換えのみで済むからです。

**Comment by yuki-js** [comment]
ディレクトリ構造やファイル名を保持できないストレージに移動することも考えたほうがいいかもしれない。まあここまで考えても現状ナンセンスかもしれないけど

**Comment by AsagaKosho** [comment]
@nandenjin 
> updated_at がないテーブルがあるのはどういう意図です？

該当のテーブルではデータの更新は発生せず、追加あるいは削除の操作のみを想定していたため、このようにしました。積極的な理由というよりかは、ある意味がないのではと考えたからです。

> 表記ゆれ、email 

修正します

> organization_data の data が抽象的で事実上意味を持っていない

どのような命名が望ましいですか？

> このテーブルがあくまで団体に紐づく情報の集合であるとするにしても、ポスターは団体の属性ではなく、独立した実体なので別テーブルであるべきでは？

organization_data_other_imageと統合し、organization_data_imageとして、image_type属性にposterまたはotherを入れるというのを思いつきましたが、どうでしょう？（処理系を統一できて良さそう？）

> 変更されなかったこれ↓についてはどういう意図ですか？🤔

結合キーを明確に示すためです。

**Comment by nandenjin** [comment]
@asagatto777 

> 該当のテーブルではデータの更新は発生せず、追加あるいは削除の操作のみを想定していたため、このようにしました。積極的な理由というよりかは、ある意味がないのではと考えたからです。

さっきのコメントがどうも伝わってないような気がしたのですが「将来的に更新する機能が加わることを想定されるものも含めて、全テーブルでフォーマットを合わせておく」方がいいのではないか、という意図でした。

将来的にこれらのテーブルに変更可能なカラムが増えて`updated_at`を（`created_at`の値に揃えた初期値で）作ることになることは十分考えうると思うのです。これが金融取引のログのように後から上書きしてはいけないことが（将来にわたって）保証されるデータなのであれば話は別ですが、そうでなければ後方互換性として「ある意味がない」ことにはならないと思います。

> organization_data の data が抽象的で事実上意味を持っていない
> どのような命名が望ましいですか？

うーん、難しいですけど `organization_pages` とか……？機能が入れ替わるなら後方互換としてなるべく衝突しないものを選びたいですね……あんま楽しくはなさそうですけど、`organization_pages_v1`みたくポストフィックス入れるとか……

> organization_data_other_imageと統合し、organization_data_imageとして、image_type属性にposterまたはotherを入れるというのを思いつきましたが、どうでしょう？（処理系を統一できて良さそう？）

その場合pdfはどこで扱うことになるんですか？こんな感じ↓ってこと？

| image_id | image_filename | image_type | image_format |
| --- | --- | --- | --- |
| number | string | enum | enum |
| 一意なID | ファイル名 | poster / other | jpg / png / pdf / ... |

**Comment by AsagaKosho** [comment]
@nandenjin 
返信遅くなり申し訳ございません。

`updated_at` はすべてのテーブルに追加する方針とします。

`organization_contents` だとどうだろうとふと思いつきましたがどうですかね…？

PDFのことを考慮していませんでした。修正版を後ほど追記します。

**Comment by AsagaKosho** [comment]
# organizations
- 団体の基礎情報を格納
- **予めこちらで登録し、基本的には変更しない**
- 主キー： organization_id

**organization_id** | organization_name | organization_type | activity_type | created_at | updated_at 
-- | -- | -- | -- | -- | --
団体ID<br>（既存システムで付与済みのもの） | 団体名 | 団体種別<br>（一般学生団体・課外活動団体） | 活動種別<br>（芸術系・文化系・体育系） | データ入力日時 | データ更新日時

# organization_contents
- 各団体が編集するデータを格納
- 主キー： organization_id

organization_id | activity_introduction | website | twitter | instagram | created_at | updated_at 
-- | -- | -- | -- | -- | -- | -- |
団体ID<br>（既存システムで付与済みのもの） | 活動紹介 | WebサイトURL | Twitterスクリーンネーム | Instagram ID | データ入力日時 | データ更新日時

# organization_contents_image
- 各団体のポスターのPDFおよび画像データ・その他画像の画像データのファイル名を格納
- 主キー： organization_id, image_filename

organization_id | image_filename | image_type | created_at | updated_at 
-- | -- | -- | -- | --
団体ID<br>（既存システムで付与済みのもの） | ファイル名 | ファイル種別<br>（poster_pdf, poster_converted_image. other_image） | データ入力日時 | データ更新日時

# organization_members
- 団体とユーザの紐付け
- 主キー： user_id, organization_id

user_id | organization_id | created_at | updated_at
-- | -- | -- | --
ユーザーID（Firebaseから付与） | 所属団体の団体ID | データ入力日時 | データ更新日時

# organization_member_invitations
- 団体への招待中の未登録ユーザ

invitation_id | mail | organization_id | created_at | updated_at 
-- | -- | -- | -- | --
招待ID | メールアドレス<br>（sアドレス） | 団体ID | データ入力日時 | データ更新日時

**Comment by AsagaKosho** [comment]
@nandenjin 
↑ここまでの議論を一通り反映させました。（未確定のものも含む）

**Comment by nandenjin** [comment]
@asagatto777 

> `organization_contents`だとどうだろうとふと思いつきましたがどうですかね…？

あー良さげ、残りのも含めてありがとうございます！🙇‍♂️🙇‍♂️🙇‍♂️ お疲れ様です！！

**Comment by AsagaKosho** [comment]
データ型も追記して確定版作ります！

**Comment by nandenjin** [comment]
@asagatto777 あー、手間じゃなければSQLファイル作ってPRとか投げてくれると話早いかもです あとでコードに起こす時にも便利やし

**Comment by AsagaKosho** [comment]
@nandenjin 
一旦ここでまとめてからSQLにしますー（頭が混乱しそう）

**Comment by AsagaKosho** [comment]
いや、いいかやっぱりSQLでプルリクします。
ルートディレクトリに置いていいですか？

**Comment by nandenjin** [comment]
@asagatto777 ありがとうございます、とりまルートでいいと思います！よろしくです

**Comment by AsagaKosho** [comment]
@nandenjin 
団体情報の公開・非公開設定を追加してはどうかなと考えたのですが、いかがですか？
また、入れるとしたらどこに入れるべきですか？

**Comment by nandenjin** [comment]
@asagatto777 ドラフト機能とか一時的な公開取り下げに使うって解釈でいいです？入れるとしたらcontentsテーブルに`published`みたいなキーで入れるとかかな🤔

**Comment by AsagaKosho** [comment]
@nandenjin 
はい、そうです。
`is_published` カラムを作ってそこにbit型で真偽値を入れる形でどうですか?

**Comment by AsagaKosho** [comment]
大学の担当課および新推委さんとの話し合いによって少し仕様に変更が加わるため、DB構造も一部変更予定です。

**Comment by AsagaKosho** [comment]
一部システム仕様変更に伴うDB構造の変更を反映したものを、明日2月1日中にプルリク送ります。
（FYI. @nandenjin @mkobayashime @yuki-js ）

**Comment by AsagaKosho** [comment]
@nandenjin @mkobayashime @yuki-js 
変更点を加えた内容です。SQLは後ほど作成しますので、ひとまずご確認いただければ。
主な変更点としては、ポスターPDFの廃止（「メイン画像」として画像形式で受付）、団体情報への公開設定の追加、キャッチコピーの追加、YouTube動画の埋め込みに対応、システム運用者からのお知らせや固定ページ機能の追加、イベント情報の追加、ユーザ権限の区別を追加です。

@nandenjin 
users テーブルの内容ってFirebaseに置く形で対応するのも可能ですかね？

# organizations
- 団体の基礎情報を格納
- **予めこちらで登録し、基本的には変更しない**
- 主キー： organization_id

**organization_id** | organization_name | organization_type | activity_type | created_at | updated_at 
-- | -- | -- | -- | -- | --
団体ID<br>（既存システムで付与済みのもの） | 団体名 | 団体種別<br>（一般学生団体・課外活動団体） | 活動種別<br>（芸術系・文化系・体育系） | データ入力日時 | データ更新日時

# organization_contents
- 各団体が編集するデータを格納
- 主キー： organization_id

organization_id | catchphrase | activity_introduction | website | twitter | instagram | is_published | created_at | updated_at 
-- | -- | -- | -- | -- | -- | -- | -- | --
団体ID<br>（既存システムで付与済みのもの） | キャッチコピー（20字以内?） | 活動紹介 | WebサイトURL | Twitterスクリーンネーム | Instagram ID | 公開設定 | データ入力日時 | データ更新日時

# organization_contents_image
- 各団体の~ポスターのPDFおよび画像データ~メイン画像のデータ・その他画像の画像データのファイル名を格納
- 主キー： organization_id, image_filename

organization_id | image_filename | image_type | created_at | updated_at 
-- | -- | -- | -- | --
団体ID<br>（既存システムで付与済みのもの） | ファイル名 | ファイル種別<br>（~poster_pdf~, poster_converted_image. other_image） | データ入力日時 | データ更新日時

# organization_contents_youtube_links
- 団体詳細ページに埋め込むYouTube動画のリンク
- 主キー： yt_link_id

yt_link_id | organization_id | link | created_at | updated_at 
-- | -- | -- | -- | -- |
リンクID | 団体ID | リンク | データ入力日時 | データ更新日時

# organization_events
- 各団体のイベント情報（イベント名、イベント開始終了日時、イベント詳細）を格納
- 主キー： event_id (AUTO_INCREMENT)

event_id | organization_id | event_name | event_detail | start_date | start_time | end_date | end_time | is_published | is_admin | created_at | updated_at 
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
イベントID | 団体ID | イベント名 | イベント詳細 | 開始日 | 開始時刻 | 終了日 | 終了時刻 | 公開設定 | システム運用者により追加されたイベントか否か | データ入力日時 | データ更新日時

# users
- ユーザ一覧（従来案ではFirebaseで全て管理しシステムでは保持しない予定だったが、権限管理の必要のため追加）
- 主キー： user_id
- general: 各団体の担当者、 admin: 新歓祭推進委員会およびWebページ学生委員会の運用担当者

user_id | name | authority | created_at | updated_at 
-- | -- | -- | -- | -- |
ユーザーID（Firebaseから付与） | 氏名(表示名) | 権限(general, admin) | データ入力日時 | データ更新日時

# organization_members
- 団体とユーザの紐付け
- 主キー： user_id, organization_id

user_id | organization_id | created_at | updated_at
-- | -- | -- | --
ユーザーID（Firebaseから付与） | 所属団体の団体ID | データ入力日時 | データ更新日時

# organization_member_invitations
- 団体への招待中の未登録ユーザ

invitation_id | mail | organization_id | created_at | updated_at 
-- | -- | -- | -- | --
招待ID | メールアドレス<br>（sアドレス） | 団体ID | データ入力日時 | データ更新日時

# pages
- システム運用者が作成する固定ページ
- 主キー： page_id

page_id | page_title | page_slug | page_content | is_published | created_at | updated_at 
-- | -- | -- | -- | -- | -- | -- |
ページID | ページ名 | URL用slug | ページ内容 | 公開設定 | データ入力日時 | データ更新日時

# announcements
- システム運用者からのお知らせ
- 主キー： announcement_id

announcement_id | announcement_title | announcement_content | is_published | created_at | updated_at 
-- | -- | -- | -- | -- | -- |
お知らせID | お知らせタイトル | お知らせ内容 | 公開設定 | データ入力日時 | データ更新日時

**Comment by nandenjin** [comment]
> users テーブルの内容ってFirebaseに置く形で対応するのも可能ですかね？

Firebase AuthenticationのDBはカスタムフィールドを作らせてくれないので、独自にテーブル必要と思う〜

**Comment by nandenjin** [comment]
### `organization_contents_image`

これだけテーブル名が単数なので複数にしたほうがよさそう

### `organization_contents_image` > `filename`

これパスじゃなくてファイル名でいいんだっけ

### `organization_contents_youtube_links` / & > `yt_link_id`

`youtube`か`yt`かどちらかに統一しないとあとでカオスになりそう

### `organization_contents`

#### `catchphrase`

普通に`title`じゃあかんの？（[Dublin Core](https://ja.wikipedia.org/wiki/Dublin_Core#%E5%9F%BA%E6%9C%AC%E8%A8%98%E8%BF%B0%E8%A6%81%E7%B4%A0%E4%B8%80%E8%A6%A7)とかに準拠できるところはしたほうが良いように感じる）

#### `activity_introduction`

これMarkdownがはいるところであってる？主観かもしれんけど単に`content`とかしたほうが実情に合う気がした……どうせ活動紹介以外のこともいっぱい書かれるだろうし……（WordPressの編集フィールドみたいなイメージ）

#### 更新時の挙動

このスキーマだと団体から更新かけたときに、adminの承認を得るまで非公開にせざるを得ないように感じたけどその挙動でいいの？

たとえば1団体につきrevisionを複数作って、

* Ex: それぞれのrevisionに対してreview queueテーブルから参照する
* Ex: それぞれのrevisionにreview_statusフラグを作って、`review_status=accepted`のもののうち最新版が表示されるようにする
 
とかやると、審査中も公開コンテンツが消えなくてすむよねとおもったり

### `organization_events`

#### `start_date | start_time | end_date | end_time`

dateとtimeで分ける必要ある？`DATETIME` 型にすればstartとendひとつずつにできる

#### 更新時の挙動

同上

#### `is_admin`

用途がちょっとよくわかんなかった このフィールドと`organization_id`の意義が事実上かぶる気がするので、統合可能ならやったほうがよいのでは（adminを意味する`organization_id`を作るとか）

### `organization_member_invitations`

#### 存在意義

これこの形で保持して、その後どういうフローで使うのかなというのは気になる（たぶんこっちの頭の中にはFirebase Authenticationの仕組みが入ってるけどそっちで考慮できてないのが原因だと思うので要相談）

#### `mail`

:x: `mail`
:o: `email`

**Comment by nandenjin** [comment]
上のレビュー問題なんですが以下のような解決策でどうでしょう（すみません @AsagaKosho と個別に相談してしまった）

- contentsは団体ごとに複数の版を持つことができるようにする
- contentsにはdraft/completed/deletedのステートを作る
- completedになったもののうち最新のものがレビュー対象になる
- review結果のテーブルを新規につくる
  - review完了後は編集できなくなる（版を複製することで再提出できる）
- review済みのもののうち最新のものが公開される
- reviewテーブルは上記と同様にしてeventsにも共通に使えるようにする
- 名前の整合性がとれなくなるので、ここまでcontentsで読んでたものをintroductionに、contentsは団体から提出されるintroductionとeventをまとめた名称にする

あとやることがあるとすれば、同じcontentsに属するrevisionを一旦全部無効にできるようにcontentsとrevisionを別テーブルに分けるとかですかね？上のコメントで指摘した他の事項は引き続き要別途対応

**Comment by AsagaKosho** [comment]
@nandenjin  コメントありがとうございます。
ひとまず今判断できる点についてご返信します。（他の点については後ほど個別に相談・整理して、こちらで結果を報告いたします。）

> organization_contents_image
> これだけテーブル名が単数なので複数にしたほうがよさそう

ミスです、修正します。

> organization_contents_image > filename
> これパスじゃなくてファイル名でいいんだっけ

上の方で@yuki-jsと議論していますのでご参照いただければ。

> organization_contents_youtube_links / & > yt_link_id
> youtubeかytかどちらかに統一しないとあとでカオスになりそう

至極そのとおりです

> start_date | start_time | end_date | end_time
> dateとtimeで分ける必要ある？DATETIME 型にすればstartとendひとつずつにできる

日毎で絞り込む際にSQLのクエリを組み立てやすいという理由です。

**Comment by AsagaKosho** [comment]
> organization_contents_image > filename
> これパスじゃなくてファイル名でいいんだっけ

パス名にします。

> catchphrase
> 普通にtitleじゃあかんの？（Dublin Coreとかに準拠できるところはしたほうが良いように感じる）

titleで

organization_eventsのis_adminは削除
organizationsにis_admin追加

contents, events の承認スキームは @nandenjin の提案をそのまま受け入れる形で
review(contents_id, type(contents or events) , result, reason)

mail->email

**Comment by AsagaKosho** [comment]
![aww-board](https://user-images.githubusercontent.com/17997951/107229755-8aeb9900-6a61-11eb-8375-97c8f4cd8639.png)

**Comment by AsagaKosho** [comment]
@nandenjin 諸々の修正と変更を加えました。ご確認ください。
# organizations

- 団体の基礎情報を格納
- **予めこちらで登録し、基本的には変更しない**
- 主キー： organization_id

| **organization_id**                        | organization_name    | organization_type                                       | activity_type                                         | is_admin                       | created_at                                     | updated_at                                                   |
| ------------------------------------------ | -------------------- | ------------------------------------------------------- | ----------------------------------------------------- | ------------------------------ | ---------------------------------------------- | ------------------------------------------------------------ |
| int(32) NOT NULL                           | varchar(64) NOT NULL | enum('課外活動団体', '一般学生団体', 'その他') NOT NULL | enum('体育系', '文化系', '芸術系', 'その他') NOT NULL | bit(1) NOT   NULL DEFAULT b'0' | timestamp NOT NULL DEFAULT current_timestamp() | timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() |
| 団体ID<br>（既存システムで付与済みのもの） | 団体名               | 団体種別<br>（一般学生団体・課外活動団体）              | 活動種別<br>（芸術系・文化系・体育系）                | 管理用団体か否か               | データ入力日時                                 | データ更新日時                                               |

# organization_introductions
- 各団体が編集するデータを格納
- 主キー： introduction_id

| introduction_id  | organization_id                            | title                      | activity_introduction | website      | twitter                 | instagram    | status                                                       | created_at                                     | updated_at                                                   |
| ---------------- | ------------------------------------------ | -------------------------- | --------------------- | ------------ | ----------------------- | ------------ | ------------------------------------------------------------ | ---------------------------------------------- | ------------------------------------------------------------ |
| int(32) NOT NULL | int(32) NOT NULL                           | varchar(64) NOT NULL       | mediamtext            | varchar(255) | varchar(255)            | varchar(255) | enum('draft', 'submitted', 'rejected',  'published') NOT NULL DEFAULT 'draft' | timestamp NOT NULL DEFAULT current_timestamp() | timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() |
| 紹介文等ID       | 団体ID<br>（既存システムで付与済みのもの） | キャッチコピー（20字以内） | 活動紹介              | WebサイトURL | Twitterスクリーンネーム | Instagram ID | 公開状態                                                     | データ入力日時                                 | データ更新日時                                               |

# organization_introductions_images
- 各団体のメイン画像のデータ・その他画像の画像データのファイル名を格納
- 主キー：image_id (AUTO_INCREMENT)

| image_id         | introduction_id  | image_path            | image_type                                  | created_at                                     | updated_at                                                   |
| ---------------- | ---------------- | --------------------- | ------------------------------------------- | ---------------------------------------------- | ------------------------------------------------------------ |
| int(32) NOT NULL | int(32) NOT NULL | varchar(255) NOT NULL | enum('main_image', 'other_image')           | timestamp NOT NULL DEFAULT current_timestamp() | timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() |
| 画像ID           | 紹介文等ID       | ファイル名            | ファイル種別<br>（main_image, other_image） | データ入力日時                                 | データ更新日時                                               |

# organization_introductions_youtube_links
- 団体詳細ページに埋め込むYouTube動画のリンク
- 主キー： youtube_link_id

| youtube_link_id  | introduction_id  | link                  | created_at                                     | updated_at                                                   |
| ---------------- | ---------------- | --------------------- | ---------------------------------------------- | ------------------------------------------------------------ |
| int(32) NOT NULL | int(32) NOT NULL | varchar(255) NOT NULL | timestamp NOT NULL DEFAULT current_timestamp() | timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() |
| リンクID         | 紹介文等ID       | リンク                | データ入力日時                                 | データ更新日時                                               |

# organization_events
- 各団体のイベント情報（イベント名、イベント開始終了日時、イベント詳細）を格納
- 主キー： event_id (AUTO_INCREMENT)

| event_id         | organization_id  | event_name           | event_detail | start_date    | start_time    | end_date      | end_time       | status                                                       | created_at                                     | updated_at                                                   |
| ---------------- | ---------------- | -------------------- | ------------ | ------------- | ------------- | ------------- | -------------- | ------------------------------------------------------------ | ---------------------------------------------- | ------------------------------------------------------------ |
| int(32) NOT NULL | int(32) NOT NULL | varchar(64) NOT NULL | mediumtext   | date NOT NULL | time NOT NULL | date NOT NULL | time NOT  NULL | enum('draft', 'submitted', 'rejected',  'published') NOT NULL DEFAULT 'draft' | timestamp NOT NULL DEFAULT current_timestamp() | timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() |
| イベントID       | 団体ID           | イベント名           | イベント詳細 | 開始日        | 開始時刻      | 終了日        | 終了時刻       | 公開状態                                                     | データ入力日時                                 | データ更新日時                                               |

# reviews

| review_id        | content_type                              | content_id                        | result                                 | reason                             |
| ---------------- | ----------------------------------------- | --------------------------------- | -------------------------------------- | ---------------------------------- |
| int(32) NOT NULL | enum('introduction', 'event') NOT NULL    | int(32) NOT NULL                  | enum('published', 'rejected') NOT NULL | mediumtext                         |
| レビューID       | レビュー対象の種別（introduction, event） | レビュー対象の紹介文等/イベントID | 結果（published, rejected）            | 理由（`result=="rejected"`の場合） |



# users

- ユーザ一覧（従来案ではFirebaseで全て管理しシステムでは保持しない予定だったが、権限管理の必要のため追加）
- 主キー： user_id
- general: 各団体の担当者、 reviewer:新歓祭推進委員会およびWebページ学生委員会の運用担当者、 admin: Webページ学生委員会の運用担当者、開発担当者

| user_id                        | name         | authority                                                    | created_at                                     | updated_at                                                   |
| ------------------------------ | ------------ | ------------------------------------------------------------ | ---------------------------------------------- | ------------------------------------------------------------ |
| varchar(128) NOT  NULL         | varchar(64)  | enum('general', 'reviewer', admin) NOT NULL DEFAULT 'general' | timestamp NOT NULL DEFAULT current_timestamp() | timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() |
| ユーザーID（Firebaseから付与） | 氏名(表示名) | 権限(general, reviewer, admin)                               | データ入力日時                                 | データ更新日時                                               |

# organization_members
- 団体とユーザの紐付け
- 主キー： user_id, organization_id

| user_id                        | organization_id  | created_at                                     | updated_at                                                   |
| ------------------------------ | ---------------- | ---------------------------------------------- | ------------------------------------------------------------ |
| varchar(128) NOT  NULL         | int(32) NOT NULL | timestamp NOT NULL DEFAULT current_timestamp() | timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() |
| ユーザーID（Firebaseから付与） | 所属団体の団体ID | データ入力日時                                 | データ更新日時                                               |

# organization_member_invitations
- 団体への招待中の未登録ユーザ

| invitation_id    | email                           | organization_id  | created_at                                     | updated_at                                                   |
| ---------------- | ------------------------------- | ---------------- | ---------------------------------------------- | ------------------------------------------------------------ |
| int(32) NOT NULL | varchar(255) NOT NULL           | int(32) NOT NULL | timestamp NOT NULL DEFAULT current_timestamp() | timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() |
| 招待ID           | メールアドレス<br>（sアドレス） | 団体ID           | データ入力日時                                 | データ更新日時                                               |

# pages
- システム運用者が作成する固定ページ
- 主キー： page_id

| page_id          | page_title           | page_slug            | page_content | is_published                 | created_at                                     | updated_at                                                   |
| ---------------- | -------------------- | -------------------- | ------------ | ---------------------------- | ---------------------------------------------- | ------------------------------------------------------------ |
| int(32) NOT NULL | varchar(64) NOT NULL | varchar(64) NOT NULL | mediumtext   | bit(1) NOT NULL DEFAULT b'0' | timestamp NOT NULL DEFAULT current_timestamp() | timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() |
| ページID         | ページ名             | URL用slug            | ページ内容   | 公開設定                     | データ入力日時                                 | データ更新日時                                               |

# announcements
- システム運用者からのお知らせ
- 主キー： announcement_id

| announcement_id  | announcement_title   | announcement_content | is_published                 | created_at                                     | updated_at                                                   |
| ---------------- | -------------------- | -------------------- | ---------------------------- | ---------------------------------------------- | ------------------------------------------------------------ |
| int(32) NOT NULL | varchar(64) NOT NULL | mediumtext           | bit(1) NOT NULL DEFAULT b'0' | timestamp NOT NULL DEFAULT current_timestamp() | timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() |
| お知らせID       | お知らせタイトル     | お知らせ内容         | 公開設定                     | データ入力日時                                 | データ更新日時                                               |
