### ISSUE TITLE
API仕様の決定

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web-api#3]
APIの入出力の仕様を決定します。

**Comment by AsagaKosho** [comment]
@nandenjin 
Firebaseでの認証とAPIシステムでの認可についての仕様の策定をお願いします。（アカウント作成時も含め）

**Comment by nandenjin** [comment]
## `/v2/organizations`
  * `GET` list / get (`/ID`)
  * `POST` create / put (`/ID`)
  * `DELETE` (`/ID`)
## `/v2/introductions`

  * `GET` list (未認証時は公開verのみ返す) (実運用ではすべて `?organization=ID`) / get (`/ID`)
  * `POST` create / put / duplicate (`?from=ID`)
  * `DELETE` (`/ID`)
## `/v2/events`
  * `GET` list (未認証時は公開verのみ返す) (`?organization=ID` または `?from=YYYYMMDD&to=YYYYMMDD`) / get (`/ID`)
  * `POST` create / put
  * `DELETE` (`/ID`)
## `/v2/introductions/ID/review`
  * `GET` get (団体用)
  * `POST` create (管理者用)
  * `DELETE` (管理者用)
 ※団体用画面でも取得する必要があるのは`status=COMPLETED`のもののみ
## `/v2/reviews`
  * `GET` list (管理者用)

## `/v2/pages`
* `GET` list / get (`/ID`)
* `POST` create / put
* `DELETE`

## `/v2/announcements`
* `GET` list / get (`/ID`)
* `POST` create / put
* `DELETE`

## `/v2/users`
* `GET` list / get (`/ID`)
* `POST` create / put
* `DELETE`

## `/v2/memberships`
* `GET` list (`?user=ID` または `?organization=ID`)
* `POST` create
* `DELETE`

## `/v2/invitations`
* `GET` list (`?user=ID` または `?organization=ID`)
* `POST` create
* `DELETE`

**Comment by AsagaKosho** [comment]
@nandenjin 
エンドポイントの設定に関しては問題ないと思います。パラメータおよび~返り血~返り値について引き続き議論しましょう。

**Comment by nandenjin** [comment]
@AsagaKosho 

![20150618115141.png](https://user-images.githubusercontent.com/7803255/107518608-8dc9c380-6bf2-11eb-9aa0-2390f1bb337a.png)

**Comment by AsagaKosho** [comment]
@nandenjin 
あっ………返り値です…
